name = "cf-realtime"
main = "index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "REALTIME_ROOM"
class_name = "RealtimeRoom"

[vars]
REALTIME_ENABLED = "true"

[observability]
enabled = true