name = "cf-api"
main = "server/api-worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "cf-nocode-db"
database_id = "3bf43ef3-714b-4533-b788-72910d944e49" # Placeholder for local development

[vars]
JWT_SECRET = "your-secret-key-change-in-production"

[observability]
enabled = true
