name = "cf-storage"
main = "index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "FILE_BUCKET"
bucket_name = "cf-nocode-files"

[vars]
STORAGE_ENABLED = "true"
MAX_FILE_SIZE = "104857600"

[observability]
enabled = true